import { useEffect,useRef,useState } from "react";
import { Plus,Trash2 } from "lucide-react";
import type { Note } from "./types";
import { emptyResearchProfile,type ResearchProfileDraft,type ResearchProfileResponse } from "./researchTypes";
import { useSaveResearchProfile } from "./researchHooks";

function draftFrom(profile:ResearchProfileResponse|null):ResearchProfileDraft{if(!profile)return emptyResearchProfile();const map=new Map(profile.contributions.map((x,i)=>[x.id,`c-${i}-${x.id}`]));return {...profile,contributions:profile.contributions.map((x,i)=>({...x,client_id:`c-${i}-${x.id}`})),experiments:profile.experiments.map((x,i)=>({...x,client_id:`e-${i}-${x.id}`,supports_contribution_client_ids:x.contribution_ids.map(id=>map.get(id)!).filter(Boolean)}))};}
const split=(value:string)=>value.split(",").map(x=>x.trim()).filter(Boolean);
export function ResearchProfileEditor({note,profile}:{note:Note;profile:ResearchProfileResponse|null}){
 const [draft,setDraft]=useState(()=>draftFrom(profile));const [dirty,setDirty]=useState(false);const revision=useRef(0);const save=useSaveResearchProfile(note.id);
 const change=(next:ResearchProfileDraft)=>{revision.current+=1;setDraft(next);setDirty(true);};
 useEffect(()=>{if(!dirty||save.isPending)return;const rev=revision.current;const timer=setTimeout(()=>save.mutate(draft,{onSuccess:()=>{if(revision.current===rev)setDirty(false);}}),1800);return()=>clearTimeout(timer);},[dirty,draft,save]);
 const field=(key:keyof ResearchProfileDraft,label:string)=><label className="block text-sm"><span className="mb-1 block font-medium">{label}</span><textarea rows={3} value={draft[key] as string} onChange={e=>change({...draft,[key]:e.target.value})} className="input" /></label>;
 const toggleEvidence=(ids:string[],id:string)=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id];
 return <div className="min-h-0 flex-1 overflow-y-auto p-5"><div className="mb-4 text-right text-xs text-gray-400">{save.isError?"保存失败":save.isPending?"正在保存…":dirty?"等待保存…":"已保存"}</div><div className="grid gap-4 md:grid-cols-2">{field("background","研究背景")}{field("prior_work_limitations","前人工作局限")}{field("research_problem","研究问题")}{field("method_summary","方法概述")}</div>
 <section className="mt-6"><div className="mb-3 flex justify-between"><h2 className="font-semibold">创新点</h2><button onClick={()=>change({...draft,contributions:[...draft.contributions,{client_id:crypto.randomUUID(),problem:"",prior_limitation:"",innovation:"",solution:"",evidence_ids:[]}]})} className="text-sm text-primary-600"><Plus className="inline h-4 w-4" />添加</button></div>{draft.contributions.map((item,index)=><div key={item.client_id} className="mb-3 rounded-lg border p-4"><button className="float-right text-red-500" onClick={()=>change({...draft,contributions:draft.contributions.filter(x=>x!==item),experiments:draft.experiments.map(e=>({...e,supports_contribution_client_ids:e.supports_contribution_client_ids.filter(id=>id!==item.client_id)}))})}><Trash2 className="h-4 w-4" /></button><p className="mb-3 font-medium">创新点 {index+1}</p>{(["problem","prior_limitation","innovation","solution"] as const).map(k=><textarea key={k} value={item[k]} placeholder={{problem:"研究问题",prior_limitation:"前人局限",innovation:"创新",solution:"解决方案"}[k]} onChange={e=>change({...draft,contributions:draft.contributions.map(x=>x===item?{...x,[k]:e.target.value}:x)})} className="input mb-2" />)}<EvidenceChecks note={note} ids={item.evidence_ids} toggle={id=>change({...draft,contributions:draft.contributions.map(x=>x===item?{...x,evidence_ids:toggleEvidence(x.evidence_ids,id)}:x)})}/></div>)}</section>
 <section className="mt-6"><div className="mb-3 flex justify-between"><h2 className="font-semibold">实验</h2><button onClick={()=>change({...draft,experiments:[...draft.experiments,{client_id:crypto.randomUUID(),task:"",datasets:[],baselines:[],metrics:[],result:"",conclusion:"",supports_contribution_client_ids:[],evidence_ids:[]}]})} className="text-sm text-primary-600"><Plus className="inline h-4 w-4" />添加</button></div>{draft.experiments.map((item,index)=><div key={item.client_id} className="mb-3 rounded-lg border p-4"><button className="float-right text-red-500" onClick={()=>change({...draft,experiments:draft.experiments.filter(x=>x!==item)})}><Trash2 className="h-4 w-4" /></button><p className="mb-3 font-medium">实验 {index+1}</p><textarea value={item.task} placeholder="任务" onChange={e=>change({...draft,experiments:draft.experiments.map(x=>x===item?{...x,task:e.target.value}:x)})} className="input mb-2" />{(["datasets","baselines","metrics"] as const).map(k=><input key={k} value={item[k].join(", ")} placeholder={`${k}，逗号分隔`} onChange={e=>change({...draft,experiments:draft.experiments.map(x=>x===item?{...x,[k]:split(e.target.value)}:x)})} className="input mb-2" />)}{(["result","conclusion"] as const).map(k=><textarea key={k} value={item[k]} placeholder={k==="result"?"结果":"实验结论"} onChange={e=>change({...draft,experiments:draft.experiments.map(x=>x===item?{...x,[k]:e.target.value}:x)})} className="input mb-2" />)}<div className="mb-2 text-xs">支持创新点：{draft.contributions.map((c,i)=><label key={c.client_id} className="ml-2"><input type="checkbox" checked={item.supports_contribution_client_ids.includes(c.client_id)} onChange={()=>change({...draft,experiments:draft.experiments.map(x=>x===item?{...x,supports_contribution_client_ids:toggleEvidence(x.supports_contribution_client_ids,c.client_id)}:x)})} /> {i+1}</label>)}</div><EvidenceChecks note={note} ids={item.evidence_ids} toggle={id=>change({...draft,experiments:draft.experiments.map(x=>x===item?{...x,evidence_ids:toggleEvidence(x.evidence_ids,id)}:x)})}/></div>)}</section>
 <div className="grid gap-4 md:grid-cols-2">{field("results_summary","结果总结")}{field("conclusion","结论")}{field("limitations","局限")}{field("future_work","未来工作")}{field("my_thoughts","我的思考")}</div></div>;
}
function EvidenceChecks({note,ids,toggle}:{note:Note;ids:string[];toggle:(id:string)=>void}){return <div className="text-xs"><span className="font-medium">证据：</span>{note.evidence.map(e=><label key={e.id} className="ml-2"><input type="checkbox" checked={ids.includes(e.id)} onChange={()=>toggle(e.id)} /> 第{e.annotation.page_number}页</label>)}</div>}
