import { BookPlus, Check, Copy, Edit3, Filter, LocateFixed, MoreHorizontal, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";

import type { Annotation, AnnotationColor, AnnotationLineStyle, UpdateAnnotationInput } from "../types";

interface Props { annotations: Annotation[]; activeAnnotationId?: string | null; currentPage: number; isLoading: boolean; onJumpTo: (annotation: Annotation) => void; onUpdate: (id: string, input: UpdateAnnotationInput) => void; onDelete: (id: string) => void; onAddToNote: (annotation: Annotation) => void }

export function AnnotationPanel({ annotations, activeAnnotationId, currentPage, isLoading, onJumpTo, onUpdate, onDelete, onAddToNote }: Props) {
  const [scope, setScope] = useState<"all" | "page">("all");
  const [editingId, setEditingId] = useState<string | null>(null);
  const filtered = useMemo(() => scope === "page" ? annotations.filter((item) => item.page_number === currentPage) : annotations, [annotations, currentPage, scope]);
  return <div className="flex h-full min-h-0 flex-col">
    <div className="flex items-center justify-between border-b border-gray-100 px-3 py-2 dark:border-slate-700"><span className="text-xs text-gray-500">{annotations.length} 条</span><div className="flex rounded border border-gray-200 p-0.5 text-xs dark:border-slate-700"><button onClick={() => setScope("all")} className={scope === "all" ? "rounded bg-primary-50 px-2 py-1 text-primary-700" : "px-2 py-1 text-gray-500"}>全文</button><button onClick={() => setScope("page")} className={scope === "page" ? "rounded bg-primary-50 px-2 py-1 text-primary-700" : "px-2 py-1 text-gray-500"}>本页</button></div></div>
    <div className="min-h-0 flex-1 overflow-y-auto p-3">{isLoading ? <p className="text-sm text-gray-400">正在加载批注…</p> : filtered.length ? filtered.map((annotation) => <AnnotationItem key={annotation.id} annotation={annotation} active={activeAnnotationId === annotation.id} editing={editingId === annotation.id} onEdit={() => setEditingId(annotation.id)} onCancel={() => setEditingId(null)} onJumpTo={onJumpTo} onUpdate={(input) => { onUpdate(annotation.id, input); setEditingId(null); }} onDelete={onDelete} onAddToNote={onAddToNote} />) : <div className="flex h-36 flex-col items-center justify-center text-sm text-gray-400"><Filter className="mb-2 h-5 w-5" />暂无批注</div>}</div>
  </div>;
}

function AnnotationItem({ annotation, active, editing, onEdit, onCancel, onJumpTo, onUpdate, onDelete, onAddToNote }: { annotation: Annotation; active: boolean; editing: boolean; onEdit: () => void; onCancel: () => void; onJumpTo: (annotation: Annotation) => void; onUpdate: (input: UpdateAnnotationInput) => void; onDelete: (id: string) => void; onAddToNote: (annotation: Annotation) => void }) {
  const [comment, setComment] = useState(annotation.comment ?? "");
  const [color, setColor] = useState<AnnotationColor>(annotation.color ?? "yellow");
  const [lineStyle, setLineStyle] = useState<AnnotationLineStyle>(annotation.line_style ?? "solid");
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);
  const copySource = async () => { if (!annotation.selected_text) return; await navigator.clipboard.writeText(annotation.selected_text); setCopied(true); window.setTimeout(() => setCopied(false), 1200); };
  return <article id={`annotation-${annotation.id}`} className={`group mb-3 scroll-m-3 rounded-lg border p-3 transition-all duration-300 ${active ? "border-primary-500 bg-primary-50 shadow-md ring-2 ring-primary-300 dark:bg-primary-950/30" : "border-gray-100 hover:border-gray-200 dark:border-slate-700"}`} title={annotation.comment || undefined}>
    <div className="w-full text-left"><div className="mb-2 flex justify-between text-xs text-gray-400"><span>第 {annotation.page_number} 页</span><span>{annotation.type === "area" ? "区域" : annotation.type}</span></div>{annotation.selected_text && <div className="flex items-start gap-1"><p className={`${expanded ? "select-text whitespace-pre-wrap" : "truncate"} min-w-0 flex-1 text-xs leading-5`}>“{annotation.selected_text}”</p><button type="button" className="mt-0.5 shrink-0 text-gray-400 hover:text-primary-600" title={expanded ? "收起原文" : "展开完整原文"} onClick={() => setExpanded((value) => !value)}><MoreHorizontal className="h-3.5 w-3.5" /></button>{expanded && <button type="button" className="mt-0.5 shrink-0 text-gray-400 hover:text-primary-600" title="复制原文" onClick={() => void copySource()}>{copied ? <Check className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}</button>}</div>}{annotation.type === "area" && <p className="text-xs text-gray-500">Figure / Table 区域标记</p>}</div>
    {editing ? <div className="mt-2 space-y-2"><textarea value={comment} onChange={(event) => setComment(event.target.value)} className="input text-xs" rows={3} placeholder="写下你的理解…" /><div className="grid grid-cols-2 gap-2"><label className="text-[10px] text-gray-400">颜色<select className="input mt-0.5 h-7 text-xs" value={color} onChange={(event) => setColor(event.target.value as AnnotationColor)}><option value="yellow">黄色</option><option value="green">绿色</option><option value="blue">蓝色</option><option value="red">红色</option><option value="purple">紫色</option></select></label>{annotation.type === "underline" && <label className="text-[10px] text-gray-400">线型<select className="input mt-0.5 h-7 text-xs" value={lineStyle} onChange={(event) => setLineStyle(event.target.value as AnnotationLineStyle)}><option value="solid">实线</option><option value="dashed">虚线</option><option value="dotted">点线</option><option value="double">双线</option><option value="wavy">波浪线</option></select></label>}</div><div className="flex justify-end gap-2"><button className="text-xs text-gray-500" onClick={onCancel}>取消</button><button className="text-xs text-primary-600" onClick={() => onUpdate({ comment, color, ...(annotation.type === "underline" ? { line_style: lineStyle } : {}) })}>保存</button></div></div> : annotation.comment && <button type="button" className="mt-2 block w-full border-l-2 border-primary-300 pl-2 text-left text-xs text-gray-600" title="点击定位到评论原文" onClick={() => onJumpTo(annotation)}>{annotation.comment}</button>}
    <div className="mt-2 flex justify-end gap-2 opacity-0 group-hover:opacity-100"><button title="定位到原文" onClick={() => onJumpTo(annotation)} className="text-gray-400 hover:text-primary-600"><LocateFixed className="h-3.5 w-3.5" /></button><button title="添加到笔记" onClick={() => onAddToNote(annotation)} className="text-gray-400 hover:text-primary-600"><BookPlus className="h-3.5 w-3.5" /></button><button title="编辑批注" onClick={onEdit} className="text-gray-400 hover:text-primary-600"><Edit3 className="h-3.5 w-3.5" /></button><button title="删除批注" onClick={() => onDelete(annotation.id)} className="text-gray-400 hover:text-red-600"><Trash2 className="h-3.5 w-3.5" /></button></div>
  </article>;
}
