import { ChevronDown, ChevronLeft, ChevronRight, Columns3, FileSpreadsheet, Loader2, Palette, Search, Trash2, Upload, X } from "lucide-react";
import { useState } from "react";
import { useSearchParams } from "react-router-dom";
import { DisplaySettings } from "@/features/paper-list/DisplaySettings";
import { COLUMN_LABELS, PaperDataGrid } from "@/features/paper-list/PaperDataGrid";
import { useBatchDeletePapers, useBatchUpdatePapers, usePaperList, usePaperListViewSettingsQuery } from "@/features/paper-list/hooks";
import { parsePaperListQuery, patchPaperListQuery, serializePaperListQuery } from "@/features/paper-list/query";
import type { PaperListColumn, PaperListQuery, PaperListSort, PaperListViewSettings } from "@/features/paper-list/types";
import { DEFAULT_VIEW_SETTINGS, hasExplicitQuery } from "@/features/paper-list/paperListSettingsSchema";
import { usePaperListViewSettings } from "@/features/paper-list/usePaperListViewSettings";
import { EditPaperDialog } from "@/features/paper/components/EditPaperDialog";
import { useDeletePaper, usePaper } from "@/features/paper/hooks";
import { useTags } from "@/features/tag/hooks";
import { useFolders } from "@/features/folder/hooks";
import { Popover } from "@/components/overlay";
import { ImportModal } from "@/components/ImportModal";
import { exportPaperList } from "@/features/paper-list/api";

const ALL_COLUMNS=Object.keys(COLUMN_LABELS) as PaperListColumn[];
export default function PaperListPage(){const preference=usePaperListViewSettingsQuery();if(preference.isLoading)return <div className="flex h-full items-center justify-center"><Loader2 className="h-5 w-5 animate-spin"/></div>;return <PaperListWorkspace initial={preference.data??DEFAULT_VIEW_SETTINGS}/>;}

function PaperListWorkspace({initial}:{initial:PaperListViewSettings}) {
  const view=usePaperListViewSettings(initial);const preference=view.settings;const [params,navigateParams]=useSearchParams();const setParams=(next:URLSearchParams)=>{if(next.size===0)view.updateSection("query",DEFAULT_VIEW_SETTINGS.query);navigateParams(next);};const query=hasExplicitQuery(params)?parsePaperListQuery(params):preference.query;const result=usePaperList(query);const tags=useTags();const folders=useFolders();
  const [selected,setSelected]=useState<Set<string>>(()=>new Set());const [showColumns,setShowColumns]=useState(false);const [showDisplay,setShowDisplay]=useState(false);const [showImport,setShowImport]=useState(false);const [showExport,setShowExport]=useState(false);const [exportColumns,setExportColumns]=useState<Set<PaperListColumn>>(()=>new Set(ALL_COLUMNS));const [exporting,setExporting]=useState(false);const [editId,setEditId]=useState<string>();const [batchTag,setBatchTag]=useState("");const [batchFolder,setBatchFolder]=useState("");
  const batchUpdate=useBatchUpdatePapers();const batchDelete=useBatchDeletePapers();const paper=usePaper(editId);const deleteOne=useDeletePaper();
  const columns=preference.columns.order.filter(column=>preference.columns.visible.includes(column));
  const update=(patch:Partial<PaperListQuery>,reset=true)=>{const nextParams=patchPaperListQuery(serializePaperListQuery(query),patch,reset);view.updateSection("query",parsePaperListQuery(nextParams));setParams(nextParams);};
  const commitColumns=(next:PaperListViewSettings["columns"])=>view.updateSection("columns",next);
  const toggleColumn=(column:PaperListColumn)=>{const visible=preference.columns.visible.includes(column)?preference.columns.visible.filter(x=>x!==column):[...preference.columns.visible,column];commitColumns({...preference.columns,visible});};
  const move=(column:PaperListColumn,delta:number)=>{const order=[...preference.columns.order];const index=order.indexOf(column),target=index+delta;if(index<0||target<0||target>=order.length)return;[order[index],order[target]]=[order[target],order[index]];commitColumns({...preference.columns,order});};
  const doBatch=async(data:Record<string,unknown>)=>{await batchUpdate.mutateAsync({paper_ids:[...selected],...data});setSelected(new Set());};
  const deleteSelected=async()=>{if(!selected.size||!confirm(`确定删除选中的 ${selected.size} 篇论文及其 PDF 吗？此操作不可恢复。`))return;await batchDelete.mutateAsync([...selected]);setSelected(new Set());};
  return <div className={`flex h-full min-h-0 flex-col gap-3 p-4 ${preference.layout.filters_expanded?"":"paper-list-filters-collapsed"}`}>
    <header className="flex shrink-0 flex-wrap items-center gap-2"><div><h1 className="text-xl font-semibold">论文列表</h1><p className="text-xs text-gray-500">可编辑的 Paper 元数据工作表</p></div>
      <form className="relative ml-auto" onSubmit={e=>{e.preventDefault();update({q:new FormData(e.currentTarget).get("q")?.toString().trim()||undefined});}}><Search className="absolute left-2.5 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400"/><input name="q" defaultValue={query.q||""} className="input w-72 py-2 pl-8 text-sm" placeholder="检索全部列表字段…" onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();update({q:e.currentTarget.value.trim()||undefined});}}}/></form>
      <button type="button" className="btn-primary" onClick={()=>setShowImport(true)}><Upload className="h-4 w-4"/>导入论文</button>
      <Popover open={showExport} onOpenChange={setShowExport} trigger={props=><button {...props} className="btn-ghost"><FileSpreadsheet className="h-4 w-4"/>导出 Excel</button>} contentClassName="absolute right-0 z-40 mt-1 w-72 rounded-xl border bg-white p-3 shadow-xl dark:border-slate-700 dark:bg-slate-900" role="dialog"><div className="mb-2 flex items-center justify-between"><div><p className="text-xs font-semibold">导出论文列表</p><p className="text-[10px] text-gray-400">{selected.size ? `仅导出选中的 ${selected.size} 篇` : "未选择论文，将导出全部论文"}</p></div><button className="text-[10px] text-primary-600" onClick={()=>setExportColumns(new Set(ALL_COLUMNS))}>全选列</button></div><div className="grid max-h-64 grid-cols-2 gap-1 overflow-y-auto">{ALL_COLUMNS.map(column=><label key={column} className="flex items-center gap-1.5 rounded px-1 py-1 text-[11px] hover:bg-gray-50"><input type="checkbox" checked={exportColumns.has(column)} onChange={()=>setExportColumns(current=>{const next=new Set(current);if(next.has(column))next.delete(column);else next.add(column);return next;})}/>{COLUMN_LABELS[column]}</label>)}</div><button type="button" className="btn-primary mt-3 w-full justify-center" disabled={!exportColumns.size||exporting} onClick={async()=>{setExporting(true);try{await exportPaperList(selected.size?[...selected]:null,ALL_COLUMNS.filter(column=>exportColumns.has(column)));setShowExport(false);}finally{setExporting(false);}}}>{exporting?"正在生成…":"生成 Excel"}</button></Popover>
      <Popover open={showColumns} onOpenChange={setShowColumns} trigger={props=><button {...props} className="btn-ghost"><Columns3 className="h-4 w-4"/>列设置<ChevronDown className="h-3.5 w-3.5"/></button>} contentClassName="absolute right-0 z-30 mt-1 w-64 rounded-xl border bg-white p-2 shadow-xl dark:border-slate-700 dark:bg-slate-900"><p className="mb-2 px-2 text-xs font-semibold">显示与顺序</p>{ALL_COLUMNS.map(column=>{const index=preference.columns.order.indexOf(column);return <div key={column} className="flex items-center gap-2 rounded px-2 py-1 text-xs"><input type="checkbox" checked={preference.columns.visible.includes(column)} onChange={()=>toggleColumn(column)}/><span className="flex-1">{COLUMN_LABELS[column]}</span><button onClick={()=>move(column,-1)} disabled={index<=0}>↑</button><button onClick={()=>move(column,1)} disabled={index<0||index===preference.columns.order.length-1}>↓</button></div>;})}</Popover>
      <Popover open={showDisplay} onOpenChange={setShowDisplay} trigger={props=><button {...props} className="btn-ghost"><Palette className="h-4 w-4"/>显示设置</button>} contentClassName="absolute right-0 z-40 mt-1 w-80 rounded-xl border bg-white p-3 shadow-xl dark:border-slate-700 dark:bg-slate-900" role="dialog"><DisplaySettings value={preference.appearance} onClose={()=>setShowDisplay(false)} onChange={appearance=>view.updateSection("appearance",appearance)} onResetWidths={()=>commitColumns({...preference.columns,widths:{}})} onResetLayout={()=>commitColumns(DEFAULT_VIEW_SETTINGS.columns)} onResetAll={view.resetAll}/></Popover>
      <button className="btn-ghost text-xs" onClick={()=>view.updateSection("layout",{...preference.layout,filters_expanded:!preference.layout.filters_expanded})}>{preference.layout.filters_expanded?"收起筛选":"展开筛选"}</button>
    </header>
    <div className="flex shrink-0 flex-wrap items-end gap-2 rounded-xl border bg-white p-2 dark:border-slate-700 dark:bg-slate-900"><Filter label="起始年份" value={query.year_from} onChange={v=>update({year_from:v?Number(v):undefined})} type="number"/><Filter label="结束年份" value={query.year_to} onChange={v=>update({year_to:v?Number(v):undefined})} type="number"/><Filter label="期刊" value={query.journal} onChange={v=>update({journal:v||undefined})}/><Filter label="作者" value={query.author} onChange={v=>update({author:v||undefined})}/><Filter label="关键词" value={query.keyword} onChange={v=>update({keyword:v||undefined})}/><label className="text-[11px] text-gray-500">标签<select className="input mt-0.5 w-32 py-1.5 text-xs" value={query.tag_id||""} onChange={e=>update({tag_id:e.target.value||undefined})}><option value="">全部</option>{tags.data?.map(tag=><option key={tag.id} value={tag.id}>{tag.name}</option>)}</select></label><label className="text-[11px] text-gray-500">阅读状态<select className="input mt-0.5 w-28 py-1.5 text-xs" value={query.reading_status||""} onChange={e=>update({reading_status:e.target.value||undefined})}><option value="">全部</option><option value="unread">未读</option><option value="reading">阅读中</option><option value="finished">已读</option><option value="archived">已归档</option></select></label><label className="flex h-8 items-center gap-1 text-xs"><input type="checkbox" checked={query.starred||false} onChange={e=>update({starred:e.target.checked||undefined})}/>仅收藏</label><button className="btn-ghost ml-auto text-xs" onClick={()=>setParams(new URLSearchParams())}><X className="h-3.5 w-3.5"/>清除</button></div>
    <div className="flex shrink-0 items-center gap-2 text-xs"><span>共 <strong>{result.data?.total??0}</strong> 篇</span><span className="ml-auto">排序</span><select className="input w-32 py-1 text-xs" value={query.sort} onChange={e=>update({sort:e.target.value as PaperListSort})}><option value="updated_at">更新时间</option><option value="created_at">创建时间</option><option value="title">标题</option><option value="title_zh">中文标题</option><option value="publication_year">年份</option><option value="journal">期刊</option><option value="citation_count">引用数</option><option value="reading_status">阅读状态</option></select><button className="btn-ghost px-2 py-1" onClick={()=>update({order:query.order==="asc"?"desc":"asc"})}>{query.order==="asc"?"升序":"降序"}</button></div>
    {selected.size>0&&<div className="flex flex-wrap items-center gap-2 rounded-lg bg-primary-50 px-3 py-2 text-xs dark:bg-slate-800"><strong>已选择 {selected.size} 篇</strong><select className="input ml-2 py-1 text-xs" defaultValue="" onChange={e=>{if(e.target.value)doBatch({reading_status:e.target.value});e.target.value="";}}><option value="">设置阅读状态…</option><option value="unread">未读</option><option value="reading">阅读中</option><option value="finished">已读</option><option value="archived">已归档</option></select><button className="btn-ghost" onClick={()=>doBatch({starred:true})}>收藏</button><button className="btn-ghost" onClick={()=>doBatch({starred:false})}>取消收藏</button><select className="input py-1 text-xs" value={batchTag} onChange={e=>setBatchTag(e.target.value)}><option value="">选择标签…</option>{tags.data?.map(tag=><option key={tag.id} value={tag.id}>{tag.name}</option>)}</select><button className="btn-ghost" disabled={!batchTag} onClick={()=>doBatch({add_tag_ids:[batchTag]})}>添加标签</button><button className="btn-ghost" disabled={!batchTag} onClick={()=>doBatch({remove_tag_ids:[batchTag]})}>移除标签</button><select className="input py-1 text-xs" value={batchFolder} onChange={e=>setBatchFolder(e.target.value)}><option value="">选择文件夹…</option>{folders.data?.map(folder=><option key={folder.id} value={folder.id}>{folder.name}</option>)}</select><button className="btn-ghost" disabled={!batchFolder} onClick={()=>doBatch({add_folder_ids:[batchFolder]})}>添加文件夹</button><button className="btn-ghost" disabled={!batchFolder} onClick={()=>doBatch({remove_folder_ids:[batchFolder]})}>移除文件夹</button><button className="btn-ghost ml-auto text-red-600" onClick={deleteSelected}><Trash2 className="h-4 w-4"/>删除</button></div>}
    {result.isLoading?<div className="flex flex-1 items-center justify-center text-sm text-gray-500"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>正在加载论文列表…</div>:result.isError?<div className="flex flex-1 items-center justify-center text-sm text-red-600">论文列表加载失败，请重试。</div>:<PaperDataGrid rows={result.data?.items||[]} columns={columns} appearance={preference.appearance} query={query} tags={tags.data||[]} onQueryChange={patch=>update(patch)} widthPreferences={preference.columns.widths} onWidthPreferencesChange={widths=>commitColumns({...preference.columns,widths})} selected={selected} onSelectionChange={setSelected} onComplexEdit={id=>{setEditId(id);view.updateSection("layout",{...preference.layout,last_paper_id:id});}} initialScrollTop={preference.layout.scroll_top} onScrollPosition={scroll_top=>view.updateSection("layout",{...preference.layout,scroll_top},800)}/>} 
    <footer className="flex shrink-0 items-center justify-between text-xs"><label>每页 <select className="input mx-1 w-20 py-1 text-xs" value={query.page_size} onChange={e=>update({page_size:Number(e.target.value) as 25|50|100|200})}>{[25,50,100,200].map(size=><option key={size}>{size}</option>)}</select></label><div className="flex items-center gap-2"><button className="btn-ghost px-2 py-1" disabled={query.page<=1} onClick={()=>update({page:query.page-1},false)}><ChevronLeft className="h-4 w-4"/></button><span>第 {query.page} / {Math.max(result.data?.total_pages||1,1)} 页</span><button className="btn-ghost px-2 py-1" disabled={!result.data||query.page>=result.data.total_pages} onClick={()=>update({page:query.page+1},false)}><ChevronRight className="h-4 w-4"/></button></div></footer>
    {editId&&paper.data&&<EditPaperDialog paper={paper.data} onClose={()=>setEditId(undefined)} onDelete={async p=>{await deleteOne.mutateAsync(p.id);}}/>}
    {showImport&&<ImportModal onClose={()=>setShowImport(false)}/>} 
  </div>;
}
function Filter({label,value,onChange,type="text"}:{label:string;value?:string|number;onChange:(value:string)=>void;type?:string}){return <label className="text-[11px] text-gray-500">{label}<input key={String(value??"")} defaultValue={value??""} type={type} className="input mt-0.5 w-28 py-1.5 text-xs" onBlur={e=>onChange(e.target.value.trim())} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur();}}/></label>;}
