import { useRef, useState } from "react";
import { BookOpen, ExternalLink, Focus, Loader2, Network } from "lucide-react";
import { useNavigate, useSearchParams } from "react-router-dom";

import { GraphCanvas, type CanvasEdge, type CanvasNode } from "@/features/graph/GraphCanvas";
import { useCitationEdge, useCitationGraph, useGraphLayout, useSaveGraphLayout } from "@/features/graph/hooks";
import type { Point } from "@/features/graph/types";

export default function CitationGraphPage() {
  const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const paperId = params.get("paper_id") || undefined; const depth: 1 | 2 = params.get("depth") === "2" ? 2 : 1;
  const graph = useCitationGraph(paperId, depth); const scopeKey = `${paperId ? `paper:${paperId}` : "workspace"}:depth:${depth}`; const layout = useGraphLayout("citation", scopeKey); const save = useSaveGraphLayout(); const timer = useRef<number>();
  const [nodeId, setNodeId] = useState<string>(); const [edgeId, setEdgeId] = useState<string>(); const detail = useCitationEdge(edgeId); const node = graph.data?.nodes.find((item) => item.paper_id === nodeId);
  const nodes: CanvasNode[] = (graph.data?.nodes ?? []).map((item) => ({ id: item.paper_id, title: item.title, subtitle: `${item.publication_year ?? "年份未知"} · 入 ${item.incoming_count} / 出 ${item.outgoing_count}`, root: item.paper_id === paperId }));
  const edges: CanvasEdge[] = (graph.data?.edges ?? []).map((item) => ({ id: item.relation_id, source: item.source_paper_id, target: item.target_paper_id, label: "引用", origin: "reference", kind: "cites" }));
  const scope = (id?: string, nextDepth: 1 | 2 = depth) => { const next = new URLSearchParams(); if (id) next.set("paper_id", id); if (nextDepth === 2) next.set("depth", "2"); setParams(next); setNodeId(undefined); setEdgeId(undefined); };
  const schedule = (positions: Record<string, Point>) => { window.clearTimeout(timer.current); timer.current = window.setTimeout(() => save.mutate({ graphType: "citation", scopeKey, positions }), 600); };
  return <div className="flex h-full min-h-0 flex-col bg-gray-50"><header className="flex items-center justify-between border-b bg-white px-6 py-4"><div><h1 className="flex items-center gap-2 text-lg font-semibold"><Network className="h-5 w-5 text-primary-600" />引用图谱</h1><p className="mt-1 text-xs text-gray-500">只展示已解析并匹配的系统引用关系</p></div><div className="flex gap-2"><button className={!paperId ? "btn-primary" : "btn-secondary"} onClick={() => scope(undefined)}>Workspace</button><select className="input w-24 py-1.5 text-xs" value={depth} disabled={!paperId} onChange={(e) => scope(paperId, Number(e.target.value) as 1 | 2)}><option value="1">1 层</option><option value="2">2 层</option></select></div></header>
    {graph.isLoading || layout.isLoading ? <div className="flex flex-1 items-center justify-center text-sm text-gray-500"><Loader2 className="mr-2 h-4 w-4 animate-spin" />加载引用关系…</div> : graph.data && <div className="flex min-h-0 flex-1"><main className="min-w-0 flex-1 p-4"><GraphCanvas key={`${scopeKey}:${graph.data.nodes.map((n) => n.paper_id).join()}:${layout.data?.updated_at ?? "auto"}`} nodes={nodes} edges={edges} rootId={paperId} savedPositions={layout.data?.positions} selectedNodeId={nodeId} selectedEdgeId={edgeId} onPositionsChange={schedule} onNode={(id) => { setNodeId(id); setEdgeId(undefined); }} onEdge={(id) => { setEdgeId(id); setNodeId(undefined); }} /></main><aside className="w-80 overflow-y-auto border-l bg-white p-5">{node ? <div><span className="text-xs font-medium text-primary-600">论文节点</span><h2 className="mt-2 font-semibold">{node.title}</h2><p className="mt-2 text-xs text-gray-500">{node.authors.join(", ")}</p><div className="mt-5 space-y-2"><button className="btn-secondary w-full justify-center" onClick={() => navigate(`/library?q=${encodeURIComponent(node.title)}`)}><BookOpen className="h-4 w-4" />查看论文</button><button className="btn-secondary w-full justify-center" onClick={() => navigate(`/reader/${node.paper_id}`)}><ExternalLink className="h-4 w-4" />打开 Reader</button><button className="btn-primary w-full justify-center" onClick={() => scope(node.paper_id, 1)}><Focus className="h-4 w-4" />以此为中心</button></div></div> : edgeId ? <div><span className="text-xs font-medium text-primary-600">系统引用关系</span><p className="mt-3 text-xs"><b>匹配：</b>{detail.data?.match_method ?? "来源已失效"}</p><p className="mt-1 text-xs"><b>置信度：</b>{detail.data?.edge.confidence == null ? "未知" : `${Math.round(detail.data.edge.confidence * 100)}%`}</p>{detail.data?.raw_citation && <blockquote className="mt-4 border-l-2 pl-3 text-xs leading-5 text-gray-600">{detail.data.raw_citation}</blockquote>}<p className="mt-4 text-xs text-gray-400">系统 citation 由 Reference Resolution 管理，不可在图谱中编辑或删除。</p></div> : <p className="py-10 text-center text-sm text-gray-400">选择节点或引用边查看详情</p>}</aside></div>}
  </div>;
}
