import { useMemo, useState } from "react";
import { Languages, Loader2, Pencil } from "lucide-react";
import type { ReaderMode, TranslationBlock, TranslationPage } from "./types";
import { useEditTranslation } from "./hooks";

export function BilingualPage({data,mode,onTranslate,pending}:{data:TranslationPage|undefined;mode:ReaderMode;onTranslate:()=>void;pending:boolean}){
  const translations=useMemo(()=>new Map((data?.translations??[]).map(t=>[t.page_block_id,t])),[data]);
  if(!data)return <div className="flex h-full items-center justify-center text-sm text-gray-400"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>正在读取页面分区…</div>;
  if(!data.blocks.length)return <Empty text="当前 PDF 尚无页面分区，请先重新解析 PDF。"/>;
  if(!data.translations.length)return <div className="flex h-full flex-col items-center justify-center gap-3 p-6 text-center"><Languages className="h-8 w-8 text-primary-400"/><p className="text-sm text-gray-500">第 {data.blocks[0]?.page_number} 页尚未翻译</p><button className="btn-primary" disabled={pending} onClick={onTranslate}>{pending?<Loader2 className="h-4 w-4 animate-spin"/>:<Languages className="h-4 w-4"/>}翻译当前页</button></div>;
  if(mode==="paragraph")return <div className="space-y-2 overflow-y-auto p-4">{data.blocks.map(block=><div key={block.id} className="grid gap-2 rounded-lg border border-gray-200 p-3 lg:grid-cols-2 dark:border-slate-700"><p className="text-xs leading-5 text-gray-500">{block.source_text}</p><Editable translation={translations.get(block.id)}/></div>)}</div>;
  return <div className="min-h-full p-5"><div className="relative mx-auto aspect-[0.707] w-full max-w-3xl bg-white shadow-lg dark:bg-slate-900">{data.blocks.map(block=>{const value=translations.get(block.id);if(!block.bounding_box)return null;return <div key={block.id} className="absolute overflow-hidden px-1 text-gray-800 dark:text-gray-100" style={{left:`${block.bounding_box.x*100}%`,top:`${block.bounding_box.y*100}%`,width:`${block.bounding_box.width*100}%`,minHeight:`${Math.max(block.bounding_box.height*100,1.2)}%`,fontSize:"clamp(8px, .72vw, 13px)",lineHeight:1.35}} title={block.source_text}><Editable translation={value} compact/></div>})}</div></div>;
}

function Editable({translation,compact=false}:{translation:TranslationBlock|undefined;compact?:boolean}){const edit=useEditTranslation();const[draft,setDraft]=useState<string|null>(null);if(!translation)return <span className="text-xs text-gray-300">尚未翻译</span>;const value=translation.effective_translation??"";if(draft!==null)return <div className="relative z-10 rounded bg-white p-1 shadow dark:bg-slate-800"><textarea autoFocus className="input min-h-20 text-xs" value={draft} onChange={e=>setDraft(e.target.value)}/><div className="mt-1 flex gap-1"><button className="btn-primary px-2 py-1 text-[11px]" onClick={()=>edit.mutate({id:translation.id,text:draft,revision:translation.revision},{onSuccess:()=>setDraft(null)})}>保存</button><button className="btn-ghost px-2 py-1 text-[11px]" onClick={()=>setDraft(null)}>取消</button></div></div>;return <button type="button" onDoubleClick={()=>setDraft(value)} onClick={()=>{if(!compact)setDraft(value)}} className={`${compact?"h-full w-full text-left":"group flex w-full items-start justify-between text-left text-sm leading-6"}`} title="双击编辑译文"><span>{value}</span>{!compact&&<Pencil className="ml-2 mt-1 h-3 w-3 shrink-0 opacity-0 group-hover:opacity-60"/>}</button>}
function Empty({text}:{text:string}){return <div className="flex h-full items-center justify-center p-6 text-center text-sm text-gray-400">{text}</div>}
