import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createPageBlock, deletePageBlock, editTranslationBlock, estimatePageTranslation, getTranslationPage, listPageBlocks, saveManualTranslationBlock, translatePage, updatePageBlock } from "./api";
import type { PageBlockBBox } from "./api";

export function useTranslationPage(paperId:string|undefined,documentId:string|undefined,page:number,enabled=true){return useQuery({queryKey:["translation-page",paperId,documentId,page,"zh-CN"],queryFn:()=>getTranslationPage(paperId!,documentId!,page),enabled:Boolean(enabled&&paperId&&documentId),refetchInterval:(query)=>{const status=query.state.data?.translation?.status;return status&&!["completed","failed","cancelled"].includes(status)?2000:false;}});}
export function useTranslatePage(paperId:string,documentId:string,page:number){const qc=useQueryClient();return useMutation({mutationFn:async()=>{const estimate=await estimatePageTranslation(paperId,documentId,page);const cost=estimate.estimated_cost?`${estimate.currency??""} ${estimate.estimated_cost}`:"无法计算（模型未配置价格）";if(!window.confirm(`翻译第 ${page} 页\n区域：${estimate.total_blocks}\n复用：${estimate.reusable_blocks}\n预计新增 Token：${estimate.estimated_input_tokens+estimate.estimated_output_tokens}\n预计费用：${cost}\n\n使用云端 Provider 时，论文文本会发送至对应服务商。是否继续？`))throw new Error("cancelled");return translatePage(paperId,documentId,page);},onSuccess:()=>qc.invalidateQueries({queryKey:["translation-page",paperId,documentId,page]})});}
export function useEditTranslation(){const qc=useQueryClient();return useMutation({mutationFn:({id,text,revision}:{id:string;text:string|null;revision:number})=>editTranslationBlock(id,text,revision),onSuccess:()=>qc.invalidateQueries({queryKey:["translation-page"]})});}
export function useSaveManualTranslation(){const qc=useQueryClient();return useMutation({mutationFn:({paperId,documentId,pageBlockId,text,revision}:{paperId:string;documentId:string;pageBlockId:string;text:string;revision?:number})=>saveManualTranslationBlock(paperId,documentId,pageBlockId,text,revision),onSuccess:()=>qc.invalidateQueries({queryKey:["translation-page"]})});}
export function usePageBlocks(documentId:string,page:number,q=""){return useQuery({queryKey:["page-blocks",documentId,page,q],queryFn:()=>listPageBlocks(documentId,page,q)});}
export function useCreatePageBlock(documentId:string,page:number){const qc=useQueryClient();return useMutation({mutationFn:({name,boundingBox}:{name:string;boundingBox:PageBlockBBox})=>createPageBlock(documentId,page,name,boundingBox),onSuccess:()=>{qc.invalidateQueries({queryKey:["page-blocks",documentId,page]});qc.invalidateQueries({queryKey:["translation-page"]});}});}
export function useUpdatePageBlock(documentId:string,page:number){const qc=useQueryClient();return useMutation({mutationFn:({id,input}:{id:string;input:{name?:string;bounding_box?:PageBlockBBox;text_style?:{font_size:number;color:string}}})=>updatePageBlock(id,input),onSuccess:()=>{qc.invalidateQueries({queryKey:["page-blocks",documentId,page]});qc.invalidateQueries({queryKey:["translation-page"]});}});}
export function useDeletePageBlock(documentId:string,page:number){const qc=useQueryClient();return useMutation({mutationFn:deletePageBlock,onSuccess:()=>{qc.invalidateQueries({queryKey:["page-blocks",documentId,page]});qc.invalidateQueries({queryKey:["translation-page"]});}});}
