import { useState } from "react";
import { Languages, Loader2 } from "lucide-react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { createTranslation, estimateTranslation } from "./api";

export function TranslationScopeMenu({paperId,documentId,pageNumber,sectionId,onStarted}:{paperId:string;documentId:string;pageNumber:number;sectionId?:string;onStarted?:()=>void}){
  const[scope,setScope]=useState<"page"|"section"|"from_page"|"paper">("page");const client=useQueryClient();
  const mutation=useMutation({mutationFn:async()=>{const input={document_id:documentId,scope_type:scope,page_number:scope==="page"||scope==="from_page"?pageNumber:undefined,section_id:scope==="section"?sectionId:undefined,target_language:"zh-CN"};const estimate=await estimateTranslation(paperId,input);const cost=estimate.estimated_cost?`${estimate.currency??""} ${estimate.estimated_cost}`:"无法计算（模型未配置价格）";if(!window.confirm(`翻译范围：${label(scope)}\n区域：${estimate.total_blocks}\n已有译文复用：${estimate.reusable_blocks}\n预计输入：${estimate.estimated_input_tokens} Token\n预计输出：${estimate.estimated_output_tokens} Token\n预计新增费用：${cost}\n\n使用云端 Provider 时，论文文本将发送给对应服务商。是否继续？`))throw new Error("cancelled");return createTranslation(paperId,input)},onSuccess:()=>{void client.invalidateQueries({queryKey:["translation-page",paperId,documentId]});onStarted?.()}});
  return <div className="flex items-center gap-1"><select aria-label="翻译范围" className="hidden h-8 rounded-md border border-gray-200 bg-white px-2 text-xs xl:block dark:border-slate-700 dark:bg-slate-800" value={scope} onChange={event=>setScope(event.target.value as typeof scope)}><option value="page">当前页</option><option value="section" disabled={!sectionId}>当前章节</option><option value="from_page">从当前页</option><option value="paper">全文</option></select><button type="button" className="reader-toolbar-button" disabled={mutation.isPending} onClick={()=>mutation.mutate()} title={`AI 翻译：${label(scope)}`} aria-label={`AI 翻译：${label(scope)}`}>{mutation.isPending?<Loader2 className="h-4 w-4 animate-spin"/>:<Languages className="h-4 w-4"/>}</button>{mutation.isError&&<span className="max-w-40 truncate text-[10px] text-red-500" title={mutation.error instanceof Error?mutation.error.message:"翻译任务创建失败"}>翻译失败</span>}</div>;
}
function label(scope:string){return scope==="page"?"当前页":scope==="section"?"当前章节":scope==="from_page"?"从当前页开始":"全文"}
