import { useEffect, useRef, useState } from "react";
import { Bot, BookOpen, ExternalLink, Focus, Loader2, Network, Plus, Sparkles, Trash2, X } from "lucide-react";
import { useNavigate, useSearchParams } from "react-router-dom";

import { GraphCanvas, type CanvasEdge, type CanvasNode } from "@/features/graph/GraphCanvas";
import { createRelation, deleteRelation, replaceRelationEvidence, updateRelation } from "@/features/graph/api";
import { useDecideSuggestion, useGenerateSuggestions, useGraphLayout, useKnowledgeGraph, useKnowledgeRelation, useSaveGraphLayout, useSuggestions } from "@/features/graph/hooks";
import type { KnowledgeGraphEdge, KnowledgeRelation, KnowledgeRelationType, Point } from "@/features/graph/types";
import { useAnnotations } from "@/features/annotation/hooks";
import { usePaper, usePapers } from "@/features/paper/hooks";
import { useParsedReferences } from "@/features/reader/parsedReferences";

const TYPES: KnowledgeRelationType[] = ["extends", "improves", "contrasts", "supports", "uses", "similar"];
const TYPE_LABEL: Record<string, string> = { cites: "引用", extends: "扩展", improves: "改进", contrasts: "对比", supports: "支持", uses: "使用", similar: "相似" };
const ORIGIN_LABEL: Record<string, string> = { reference: "系统引用", manual: "人工", ai: "AI 已接受" };

function csv(params: URLSearchParams, key: string, fallback: string[]) { const value = params.get(key); return value ? value.split(",").filter(Boolean) : fallback; }

export default function KnowledgeGraphPage() {
  const navigate = useNavigate(); const [params, setParams] = useSearchParams();
  const paperId = params.get("paper_id") || undefined; const depth: 1 | 2 = params.get("depth") === "2" ? 2 : 1;
  const relationTypes = csv(params, "relation_types", TYPES); const origins = csv(params, "origins", ["manual", "ai"]);
  const graph = useKnowledgeGraph(paperId, depth, relationTypes, origins);
  const scopeKey = `${paperId ? `paper:${paperId}` : "workspace"}:depth:${depth}:types:${relationTypes.join("-")}:origins:${origins.join("-")}`;
  const layout = useGraphLayout("knowledge", scopeKey); const saveLayout = useSaveGraphLayout(); const saveTimer = useRef<number>();
  useEffect(() => () => window.clearTimeout(saveTimer.current), []);
  const [selectedNodeId, setSelectedNodeId] = useState<string>(); const [selectedEdgeId, setSelectedEdgeId] = useState<string>();
  const [dialog, setDialog] = useState<{ sourceId: string; relation?: KnowledgeRelation }>(); const [suggestionsOpen, setSuggestionsOpen] = useState(false);
  const relation = useKnowledgeRelation(selectedEdgeId);
  const node = graph.data?.nodes.find((item) => item.paper_id === selectedNodeId);
  const setFilter = (key: string, values: string[]) => { if (!values.length) return; const next = new URLSearchParams(params); next.set(key, values.join(",")); next.delete("page"); setParams(next); };
  const recenter = (id?: string) => { const next = new URLSearchParams(params); if (id) next.set("paper_id", id); else next.delete("paper_id"); setParams(next); setSelectedNodeId(undefined); setSelectedEdgeId(undefined); };
  const nodes: CanvasNode[] = (graph.data?.nodes ?? []).map((item) => ({ id: item.paper_id, title: item.title, subtitle: `${item.publication_year ?? "年份未知"} · ${readingLabel(item.reading_status)}`, root: item.paper_id === paperId }));
  const edges: CanvasEdge[] = (graph.data?.edges ?? []).map((item) => ({ id: item.relation_id, source: item.source_paper_id, target: item.target_paper_id, label: TYPE_LABEL[item.relation_type], origin: item.origin, undirected: item.relation_type === "similar", kind: item.relation_type }));
  const scheduleSave = (positions: Record<string, Point>) => { window.clearTimeout(saveTimer.current); saveTimer.current = window.setTimeout(() => saveLayout.mutate({ graphType: "knowledge", scopeKey, positions }), 600); };

  return <div className="flex h-full min-h-0 flex-col bg-gray-50 dark:bg-slate-950">
    <header className="border-b bg-white px-6 py-4 dark:border-slate-700 dark:bg-slate-900">
      <div className="flex items-center justify-between"><div><h1 className="flex items-center gap-2 text-lg font-semibold"><Network className="h-5 w-5 text-primary-600" />知识图谱</h1><p className="mt-1 text-xs text-gray-500">探索论文之间有方向、有语义且可追溯的研究关系</p></div>
        <div className="flex gap-2"><button className="btn-secondary" onClick={() => recenter(undefined)}>Workspace</button><select className="input w-24 py-1.5 text-xs" value={depth} disabled={!paperId} onChange={(e) => { const next = new URLSearchParams(params); next.set("depth", e.target.value); setParams(next); }}><option value="1">1 层</option><option value="2">2 层</option></select><button className="btn-primary" disabled={!paperId} onClick={() => setSuggestionsOpen(true)}><Sparkles className="h-4 w-4" />AI 关系建议</button></div>
      </div>
      <div className="mt-3 flex flex-wrap items-center gap-4 text-xs"><span className="font-medium text-gray-500">关系：</span>{[...TYPES, "cites"].map((type) => <label key={type} className="flex items-center gap-1"><input type="checkbox" checked={relationTypes.includes(type)} onChange={() => setFilter("relation_types", relationTypes.includes(type) ? relationTypes.filter((v) => v !== type) : [...relationTypes, type])} />{TYPE_LABEL[type]}</label>)}<span className="ml-3 font-medium text-gray-500">来源：</span>{["manual", "ai", "reference"].map((origin) => <label key={origin} className="flex items-center gap-1"><input type="checkbox" checked={origins.includes(origin)} onChange={() => setFilter("origins", origins.includes(origin) ? origins.filter((v) => v !== origin) : [...origins, origin])} />{ORIGIN_LABEL[origin]}</label>)}</div>
    </header>
    {graph.isLoading || layout.isLoading ? <div className="flex flex-1 items-center justify-center text-sm text-gray-500"><Loader2 className="mr-2 h-4 w-4 animate-spin" />加载知识图谱…</div> : graph.isError ? <div className="flex flex-1 items-center justify-center text-sm text-red-500">知识图谱加载失败。</div> : graph.data && <div className="flex min-h-0 flex-1"><main className="min-w-0 flex-1 p-4"><GraphCanvas key={`${scopeKey}:${graph.data.nodes.map((n) => n.paper_id).join()}:${layout.data?.updated_at ?? "auto"}`} nodes={nodes} edges={edges} rootId={paperId} savedPositions={layout.data?.positions} selectedNodeId={selectedNodeId} selectedEdgeId={selectedEdgeId} onPositionsChange={scheduleSave} onNode={(id) => { setSelectedNodeId(id); setSelectedEdgeId(undefined); }} onEdge={(id) => { setSelectedEdgeId(id); setSelectedNodeId(undefined); }} /></main>
      <aside className="w-80 overflow-y-auto border-l bg-white p-5 dark:border-slate-700 dark:bg-slate-900">{node ? <NodeInspector node={node} onOpen={() => navigate(`/library?q=${encodeURIComponent(node.title)}`)} onReader={() => navigate(`/reader/${node.paper_id}`)} onCenter={() => recenter(node.paper_id)} onCreate={() => setDialog({ sourceId: node.paper_id })} /> : selectedEdgeId ? <EdgeInspector edge={graph.data.edges.find((item) => item.relation_id === selectedEdgeId)} relation={relation.data} loading={relation.isLoading} onEvidence={(paper, page) => navigate(`/reader/${paper}${page ? `?page=${page}` : ""}`)} onEdit={() => relation.data?.origin === "manual" && setDialog({ sourceId: relation.data.source_paper_id, relation: relation.data })} onDelete={async () => { if (!relation.data || relation.data.origin !== "manual" || !window.confirm("确定删除这条人工关系吗？")) return; await deleteRelation(relation.data.source_paper_id, relation.data.id); setSelectedEdgeId(undefined); await graph.refetch(); }} /> : <p className="py-10 text-center text-sm text-gray-400">选择论文或关系查看详情</p>}</aside></div>}
    {dialog && <RelationDialog sourceId={dialog.sourceId} relation={dialog.relation} onClose={() => setDialog(undefined)} onSaved={async () => { setDialog(undefined); await graph.refetch(); }} />}
    {suggestionsOpen && paperId && <SuggestionPanel paperId={paperId} onClose={() => setSuggestionsOpen(false)} />}
  </div>;
}

function NodeInspector({ node, onOpen, onReader, onCenter, onCreate }: { node: NonNullable<ReturnType<typeof useKnowledgeGraph>["data"]>["nodes"][number]; onOpen: () => void; onReader: () => void; onCenter: () => void; onCreate: () => void }) { return <div><span className="text-xs font-medium text-primary-600">论文节点</span><h2 className="mt-2 font-semibold leading-6">{node.title}</h2><p className="mt-2 text-xs text-gray-500">{node.authors.join(", ") || "作者未知"}</p><p className="mt-1 text-xs text-gray-500">{node.publication_year ?? "年份未知"} · {readingLabel(node.reading_status)}</p><div className="mt-4 grid grid-cols-2 gap-2 text-center text-xs"><div className="rounded bg-gray-50 p-3"><b className="text-base">{node.outgoing_count}</b><p>Outgoing</p></div><div className="rounded bg-gray-50 p-3"><b className="text-base">{node.incoming_count}</b><p>Incoming</p></div></div><div className="mt-5 space-y-2"><button className="btn-secondary w-full justify-center" onClick={onOpen}><BookOpen className="h-4 w-4" />打开论文</button><button className="btn-secondary w-full justify-center" onClick={onReader}><ExternalLink className="h-4 w-4" />打开 Reader</button><button className="btn-secondary w-full justify-center" onClick={onCenter}><Focus className="h-4 w-4" />以此为中心</button><button className="btn-primary w-full justify-center" onClick={onCreate}><Plus className="h-4 w-4" />新建关系</button></div></div>; }

function EdgeInspector({ edge, relation, loading, onEvidence, onEdit, onDelete }: { edge?: KnowledgeGraphEdge; relation?: KnowledgeRelation; loading: boolean; onEvidence: (paperId: string, page?: number | null) => void; onEdit: () => void; onDelete: () => void }) { if (loading || !edge) return <p className="text-sm text-gray-400">读取关系…</p>; const readonly = relation?.origin !== "manual"; return <div><span className="text-xs font-medium text-primary-600">{TYPE_LABEL[edge.relation_type]}</span><h2 className="mt-2 text-sm font-semibold">{TYPE_LABEL[edge.relation_type]} 关系</h2><div className="mt-3 rounded-lg bg-gray-50 p-3 text-xs leading-5"><p><b>来源：</b>{ORIGIN_LABEL[edge.origin]}</p><p><b>Evidence：</b>{edge.evidence_count}</p>{relation?.confidence != null && <p><b>置信度：</b>{Math.round(relation.confidence * 100)}%</p>}{relation?.ai_provider_name && <><p><b>Provider：</b>{relation.ai_provider_name}</p><p><b>Model：</b>{relation.ai_model}</p></>}</div>{relation?.note && <p className="mt-3 text-sm leading-6">{relation.note}</p>}<div className="mt-4 space-y-2">{relation?.evidence.map((item) => <button key={item.id} className="w-full rounded border p-2 text-left text-xs hover:bg-gray-50" onClick={() => item.paper_id && onEvidence(item.paper_id, item.page_number)}><span className="font-medium">{item.annotation_id ? "Annotation" : "Reference"}{item.page_number ? ` · Page ${item.page_number}` : ""}</span><p className="mt-1 line-clamp-3 text-gray-500">{item.quote_snapshot}</p></button>)}{relation?.ai_evidence.map((item, index) => <button key={index} className="w-full rounded border border-violet-200 p-2 text-left text-xs" onClick={() => typeof item.paper_id === "string" && onEvidence(item.paper_id, typeof item.page_start === "number" ? item.page_start : undefined)}><Bot className="mr-1 inline h-3 w-3" />AI Source · Page {String(item.page_start ?? "?")}<p className="mt-1 line-clamp-3 text-gray-500">{String(item.content ?? "")}</p></button>)}</div><div className="mt-5 grid grid-cols-2 gap-2"><button className="btn-secondary justify-center" disabled={readonly} title={readonly ? "系统引用或 AI accepted 关系不可通过人工 CRUD 修改" : undefined} onClick={onEdit}>编辑</button><button className="flex items-center justify-center gap-1 rounded border border-red-200 text-sm text-red-600 disabled:opacity-40" disabled={readonly} title={readonly ? "系统维护的关系只读" : undefined} onClick={onDelete}><Trash2 className="h-4 w-4" />删除</button></div>{readonly && <p className="mt-2 text-xs text-gray-400">此关系由系统或 AI Apply 流程维护，只读展示 provenance。</p>}</div>; }

function RelationDialog({ sourceId, relation, onClose, onSaved }: { sourceId: string; relation?: KnowledgeRelation; onClose: () => void; onSaved: () => void }) {
  const papers = usePapers({ page_size: 100 }); const [targetId, setTargetId] = useState(relation?.target_paper_id ?? ""); const [type, setType] = useState<KnowledgeRelationType>((relation?.relation_type as KnowledgeRelationType) ?? "extends"); const [note, setNote] = useState(relation?.note ?? ""); const [selected, setSelected] = useState<string[]>(relation?.evidence.map((item) => item.annotation_id ? `a:${item.annotation_id}` : `r:${item.source_reference_id}`) ?? []); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const source = usePaper(sourceId); const target = usePaper(targetId || undefined); const sourceDoc = source.data?.document?.id; const targetDoc = target.data?.document?.id;
  const sourceAnnotations = useAnnotations(sourceId, sourceDoc); const targetAnnotations = useAnnotations(targetId || undefined, targetDoc); const sourceReferences = useParsedReferences(sourceDoc); const targetReferences = useParsedReferences(targetDoc);
  const choices = [...(sourceAnnotations.data ?? []), ...(targetAnnotations.data ?? [])].map((item) => ({ key: `a:${item.id}`, label: `Annotation · Page ${item.page_number}`, text: item.selected_text || item.comment || "Annotation" })).concat([...(sourceReferences.data ?? []), ...(targetReferences.data ?? [])].map((item) => ({ key: `r:${item.id}`, label: `Reference · Page ${item.page_start}`, text: item.raw_text })));
  const sourceTitle = source.data?.title ?? "Source"; const targetTitle = papers.data?.items.find((item) => item.id === targetId)?.title ?? "Target";
  const submit = async () => { if (!targetId || targetId === sourceId) return; setSaving(true); setError(""); try { const saved = relation ? await updateRelation(sourceId, relation.id, { target_paper_id: targetId, relation_type: type, note: note || null }) : await createRelation(sourceId, { target_paper_id: targetId, relation_type: type, note: note || null }); await replaceRelationEvidence(saved.id, selected.map((key) => key.startsWith("a:") ? { annotation_id: key.slice(2) } : { source_reference_id: key.slice(2) })); onSaved(); } catch (e) { setError((e as { response?: { data?: { detail?: string } } }).response?.data?.detail ?? "保存关系失败"); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl"><div className="flex justify-between"><div><h2 className="font-semibold">{relation ? "编辑人工关系" : "新建人工关系"}</h2><p className="mt-1 text-xs text-gray-500">明确 source → target 语义后再保存，不支持拖线自动建边。</p></div><button onClick={onClose}><X className="h-5 w-5" /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">Source Paper<input className="input mt-1" value={sourceTitle} disabled /></label><label className="text-sm">Target Paper<select className="input mt-1" value={targetId} onChange={(e) => setTargetId(e.target.value)}><option value="">选择论文…</option>{papers.data?.items.filter((item) => item.id !== sourceId).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="text-sm">Relation Type<select className="input mt-1" value={type} onChange={(e) => setType(e.target.value as KnowledgeRelationType)}>{TYPES.map((item) => <option key={item} value={item}>{TYPE_LABEL[item]}</option>)}</select></label><label className="text-sm sm:col-span-2">Description<textarea className="input mt-1 min-h-20" value={note} onChange={(e) => setNote(e.target.value)} /></label></div>{targetId && <div className="mt-4 rounded-lg bg-primary-50 p-3 text-sm font-medium text-primary-700">Preview: {sourceTitle} {type} {targetTitle}</div>}<div className="mt-5"><h3 className="text-sm font-medium">选择已有 Evidence</h3><p className="mb-2 text-xs text-gray-500">新证据仍需在 Reader 中创建；这里仅选择两端论文已有 Annotation / Reference。</p><div className="max-h-52 space-y-2 overflow-y-auto">{choices.map((item) => <label key={item.key} className="flex gap-2 rounded border p-2 text-xs"><input type="checkbox" checked={selected.includes(item.key)} onChange={() => setSelected((v) => v.includes(item.key) ? v.filter((x) => x !== item.key) : [...v, item.key])} /><span><b>{item.label}</b><span className="mt-1 block line-clamp-2 text-gray-500">{item.text}</span></span></label>)}{!choices.length && <p className="rounded border border-dashed p-3 text-xs text-gray-400">两篇论文暂无可选证据。</p>}</div></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-6 flex justify-end gap-2"><button className="btn-secondary" onClick={onClose}>取消</button><button className="btn-primary" disabled={saving || !targetId || targetId === sourceId} onClick={() => void submit()}>{saving ? "保存中…" : "保存关系"}</button></div></div></div>;
}

function SuggestionPanel({ paperId, onClose }: { paperId: string; onClose: () => void }) { const suggestions = useSuggestions(paperId); const generate = useGenerateSuggestions(paperId); const decide = useDecideSuggestion(paperId); const papers = usePapers({ page_size: 100 }); const title = (id: string) => papers.data?.items.find((item) => item.id === id)?.title ?? id; return <div className="fixed inset-0 z-50 flex justify-end bg-black/30"><div className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><div><h2 className="font-semibold">AI 关系建议</h2><p className="text-xs text-gray-500">Pending 建议不会出现在正式图谱中</p></div><button onClick={onClose}><X className="h-5 w-5" /></button></div><button className="btn-primary mt-5 w-full justify-center" disabled={generate.isPending} onClick={() => generate.mutate()}><Sparkles className="h-4 w-4" />{generate.isPending ? "正在分析候选论文…" : "生成关系建议"}</button><div className="mt-5 space-y-4">{suggestions.data?.filter((item) => item.status === "pending").map((item) => <article key={item.id} className="rounded-xl border p-4"><p className="text-xs text-gray-500">{title(item.source_paper_id)}</p><p className="my-2 text-center text-sm font-semibold text-primary-600">→ {TYPE_LABEL[item.relation_type]} →</p><p className="text-xs text-gray-500">{title(item.target_paper_id)}</p><p className="mt-3 text-sm leading-6">{item.reason}</p><div className="mt-3 space-y-2">{item.evidence.map((e, i) => <div key={i} className="rounded bg-violet-50 p-2 text-xs"><b>Page {e.page_start ?? "?"}</b><p className="mt-1 line-clamp-3 text-gray-600">{e.content}</p></div>)}</div><p className="mt-2 text-xs text-gray-400">{item.provider_name} · {item.model}{item.confidence != null ? ` · ${Math.round(item.confidence * 100)}%` : ""}</p><div className="mt-4 grid grid-cols-2 gap-2"><button className="btn-primary justify-center" disabled={decide.isPending} onClick={() => decide.mutate({ id: item.id, decision: "accept" })}>接受</button><button className="btn-secondary justify-center" disabled={decide.isPending} onClick={() => decide.mutate({ id: item.id, decision: "reject" })}>拒绝</button></div></article>)}{!suggestions.isLoading && !suggestions.data?.some((item) => item.status === "pending") && <p className="py-10 text-center text-sm text-gray-400">暂无 pending 建议</p>}</div></div></div>; }
function readingLabel(value: string) { return ({ unread: "未读", reading: "阅读中", finished: "已读", archived: "已归档" } as Record<string, string>)[value] ?? value; }
