/* eslint-disable react-refresh/only-export-components -- column metadata belongs to the grid */
import { Check, Filter, LoaderCircle, Pencil, X } from "lucide-react";
import { useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { FONT_MAP, FONT_SIZE, ROW_HEIGHT, type PaperListAppearance } from "./appearance";
import { calculateColumnLayout, COLUMN_LAYOUT, resetColumnWidth, resizeColumn, type WidthPreferences } from "./columnLayout";
import { useUpdatePaperCell } from "./hooks";
import type { PaperCellUpdate, PaperListColumn, PaperListQuery, PaperListRow } from "./types";
import { Popover } from "@/components/overlay";

export const COLUMN_LABELS: Record<PaperListColumn, string> = {
  title:"标题",title_zh:"中文标题",abstract:"摘要",authors:"作者",journal:"期刊",conference:"会议",publication_year:"年份",
  keywords:"关键词",tags:"标签",folders:"文件夹",doi:"DOI",arxiv_id:"arXiv",url:"链接",publisher:"出版社",
  citation_text:"标准引用",citation_count:"引用数",reading_status:"阅读状态",starred:"收藏",notes:"笔记",created_at:"创建时间",updated_at:"更新时间",
};
const readingLabels:Record<string,string>={unread:"未读",reading:"阅读中",finished:"已读",archived:"已归档"};
const editable = new Set<PaperListColumn>(["title","title_zh","abstract","journal","conference","publication_year","doi","arxiv_id","url","publisher","citation_text","citation_count","starred"]);
const longText = new Set<PaperListColumn>(["abstract","citation_text"]);

function FilterHeaderCell({column,width,query,tags,onFilter,onDrag,onCommit,onReset}:{column:PaperListColumn;width:number;query:PaperListQuery;tags:{id:string;name:string}[];onFilter:(patch:Partial<PaperListQuery>)=>void;onDrag:(delta:number)=>void;onCommit:(delta:number)=>void;onReset:()=>void}) {
  return <span className="relative block h-full min-w-0 pr-6"><HeaderCell column={column} width={width} onDrag={onDrag} onCommit={onCommit} onReset={onReset}/><span className="absolute right-2 top-1/2 -translate-y-1/2"><ColumnFilter column={column} query={query} tags={tags} onFilter={onFilter}/></span></span>;
}

function ColumnFilter({column,query,tags,onFilter}:{column:PaperListColumn;query:PaperListQuery;tags:{id:string;name:string}[];onFilter:(patch:Partial<PaperListQuery>)=>void}) {
  const [open,setOpen]=useState(false);
  const dedicated=column==="authors"?"author":column==="journal"?"journal":column==="keywords"?"keyword":null;
  const current=dedicated?String(query[dedicated]??""):column==="publication_year"?String(query.year_from===query.year_to?query.year_from??"":""):column==="tags"?query.tag_id??"":column==="reading_status"?query.reading_status??"":column==="starred"?(query.starred?"true":""):query.q??"";
  const [draft,setDraft]=useState(current);
  const active=Boolean(current);
  const apply=()=>{if(dedicated)onFilter({[dedicated]:draft.trim()||undefined});else if(column==="publication_year"){const year=Number(draft);onFilter({year_from:year||undefined,year_to:year||undefined});}else if(column==="tags")onFilter({tag_id:draft||undefined});else if(column==="reading_status")onFilter({reading_status:draft||undefined});else if(column==="starred")onFilter({starred:draft==="true"||undefined});else onFilter({q:draft.trim()||undefined});setOpen(false);};
  const clear=()=>{setDraft("");if(dedicated)onFilter({[dedicated]:undefined});else if(column==="publication_year")onFilter({year_from:undefined,year_to:undefined});else if(column==="tags")onFilter({tag_id:undefined});else if(column==="reading_status")onFilter({reading_status:undefined});else if(column==="starred")onFilter({starred:undefined});else onFilter({q:undefined});setOpen(false);};
  const isSelect=["tags","reading_status","starred"].includes(column);
  return <Popover open={open} onOpenChange={value=>{setOpen(value);if(value)setDraft(current);}} trigger={props=><button {...props} type="button" aria-label={`筛选${COLUMN_LABELS[column]}`} className={`shrink-0 rounded p-0.5 ${active?"bg-primary-100 text-primary-600":"text-gray-400 hover:bg-gray-200"}`}><Filter className="h-3 w-3"/></button>} role="dialog" contentClassName="absolute left-0 top-full z-50 mt-1 w-56 rounded-lg border border-gray-200 bg-white p-3 text-gray-700 shadow-xl dark:border-slate-700 dark:bg-slate-900 dark:text-gray-200">
    <p className="mb-2 text-xs font-semibold">筛选：{COLUMN_LABELS[column]}</p>
    {column==="tags"?<select autoFocus className="input h-8 w-full text-xs" value={draft} onChange={e=>setDraft(e.target.value)}><option value="">全部标签</option>{tags.map(tag=><option key={tag.id} value={tag.id}>{tag.name}</option>)}</select>:column==="reading_status"?<select autoFocus className="input h-8 w-full text-xs" value={draft} onChange={e=>setDraft(e.target.value)}><option value="">全部状态</option><option value="unread">未读</option><option value="reading">阅读中</option><option value="finished">已读</option><option value="archived">已归档</option></select>:column==="starred"?<select autoFocus className="input h-8 w-full text-xs" value={draft} onChange={e=>setDraft(e.target.value)}><option value="">全部</option><option value="true">仅收藏</option></select>:<><input autoFocus type={column==="publication_year"?"number":"search"} className="input h-8 w-full text-xs" value={draft} placeholder={dedicated?`搜索${COLUMN_LABELS[column]}`:"在全部字段中搜索"} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&apply()}/>{!dedicated&&column!=="publication_year"&&<p className="mt-1 text-[10px] font-normal text-gray-400">该列复用全字段服务端搜索</p>}</>}
    <div className="mt-3 flex justify-end gap-1"><button type="button" className="btn-ghost px-2 py-1 text-xs" onClick={clear}><X className="h-3 w-3"/>清除</button><button type="button" className="btn-primary px-2 py-1 text-xs" onClick={apply}>{isSelect?"应用":"搜索"}</button></div>
  </Popover>;
}

export function PaperDataGrid({rows,columns,appearance,query,tags,onQueryChange,widthPreferences,onWidthPreferencesChange,selected,onSelectionChange,onComplexEdit,initialScrollTop=0,onScrollPosition}:{rows:PaperListRow[];columns:PaperListColumn[];appearance:PaperListAppearance;query:PaperListQuery;tags:{id:string;name:string}[];onQueryChange:(patch:Partial<PaperListQuery>)=>void;widthPreferences:WidthPreferences;onWidthPreferencesChange:(value:WidthPreferences)=>void;selected:Set<string>;onSelectionChange:(value:Set<string>)=>void;onComplexEdit:(id:string)=>void;initialScrollTop?:number;onScrollPosition?:(value:number)=>void}) {
  const ref=useRef<HTMLDivElement>(null);const scroller=useRef<HTMLDivElement>(null);const scrollSaveTimer=useRef<ReturnType<typeof setTimeout>>();const [width,setWidth]=useState(1000);const [scrollTop,setScrollTop]=useState(initialScrollTop);const [heights,setHeights]=useState(()=>new Map<string,number>());const [drag,setDrag]=useState<{column:PaperListColumn;delta:number}|null>(null);
  const minimumHeight=ROW_HEIGHT[appearance.density];const viewportHeight=520;const overscan=5;
  useEffect(()=>{const node=ref.current;if(!node)return;let frame=0;const observer=new ResizeObserver(()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>setWidth(node.clientWidth));});observer.observe(node);return()=>{cancelAnimationFrame(frame);observer.disconnect();};},[]);
  useLayoutEffect(()=>{if(scroller.current&&initialScrollTop>0)scroller.current.scrollTop=initialScrollTop;},[initialScrollTop]);
  useEffect(()=>()=>{if(scrollSaveTimer.current)clearTimeout(scrollSaveTimer.current);},[]);
  const selectionWidth=40;const available=Math.max(0,width-selectionWidth-8);const baseWidths=calculateColumnLayout(columns,available,widthPreferences);const previewPreferences=drag?resizeColumn(columns,baseWidths,widthPreferences,drag.column,drag.delta):widthPreferences;const renderedWidths=calculateColumnLayout(columns,available,previewPreferences);const template=`${selectionWidth}px ${columns.map(id=>`${renderedWidths[id]}px`).join(" ")}`;
  const signature=`${columns.join(",")}|${columns.map(id=>renderedWidths[id]).join(",")}|${appearance.font_family}|${appearance.font_size}|${appearance.density}`;
  const rowKeys=rows.map(row=>`${row.id}|${row.title}|${row.title_zh||""}|${signature}`);const rowHeights=rowKeys.map(key=>heights.get(key)??minimumHeight);const offsets:number[]=[];let totalHeight=0;for(const value of rowHeights){offsets.push(totalHeight);totalHeight+=value;}
  let first=0;while(first<rows.length&&offsets[first]+rowHeights[first]<scrollTop)first++;const start=Math.max(0,first-overscan);let end=first;while(end<rows.length&&offsets[end]<scrollTop+viewportHeight)end++;end=Math.min(rows.length,end+overscan);
  const visible=useMemo(()=>rows.slice(start,end),[rows,start,end]);
  const allSelected=rows.length>0&&rows.every(row=>selected.has(row.id));
  const togglePage=()=>{const next=new Set(selected);if(allSelected)rows.forEach(row=>next.delete(row.id));else rows.forEach(row=>next.add(row.id));onSelectionChange(next);};
  const style={fontFamily:FONT_MAP[appearance.font_family],fontSize:FONT_SIZE[appearance.font_size],color:appearance.primary_text,borderColor:appearance.border};
  return <div ref={ref} data-paper-grid className="min-h-0 w-full flex-1 rounded-xl border bg-white" style={style}>
    <div className="relative z-20 grid items-center border-b px-1 font-semibold" style={{gridTemplateColumns:template,height:38,background:appearance.header_background,color:appearance.header_text,borderColor:appearance.border}}>
      <input type="checkbox" aria-label="选择当前页全部论文" checked={allSelected} onChange={togglePage}/>{columns.map(column=><FilterHeaderCell key={column} column={column} width={renderedWidths[column]} query={query} tags={tags} onFilter={onQueryChange} onDrag={delta=>setDrag({column,delta})} onCommit={delta=>{onWidthPreferencesChange(resizeColumn(columns,baseWidths,widthPreferences,column,delta));setDrag(null);}} onReset={()=>onWidthPreferencesChange(resetColumnWidth(widthPreferences,column))}/>)}
    </div>
    <div ref={scroller} className="overflow-y-auto overflow-x-hidden" style={{height:viewportHeight}} onScroll={event=>{const value=event.currentTarget.scrollTop;setScrollTop(value);if(scrollSaveTimer.current)clearTimeout(scrollSaveTimer.current);scrollSaveTimer.current=setTimeout(()=>onScrollPosition?.(value),700);}}>
      <div className="relative" style={{height:totalHeight}}>{visible.map((row,relativeIndex)=>{const index=start+relativeIndex,key=rowKeys[index];return <MeasuredRow key={key} row={row} rowKey={key} top={offsets[index]} height={rowHeights[index]} minimumHeight={minimumHeight} columns={columns} template={template} appearance={appearance} selected={selected.has(row.id)} onMeasured={value=>{const previous=heights.get(key)??minimumHeight;if(Math.abs(previous-value)<=1)return;if(index<first&&scroller.current)scroller.current.scrollTop+=value-previous;const next=new Map(heights);next.set(key,value);setHeights(next);}} onToggle={()=>{const next=new Set(selected);if(next.has(row.id))next.delete(row.id);else next.add(row.id);onSelectionChange(next);}} onComplexEdit={onComplexEdit}/>;})}
      </div>
    </div>
  </div>;
}

function HeaderCell({column,width,onDrag,onCommit,onReset}:{column:PaperListColumn;width:number;onDrag:(delta:number)=>void;onCommit:(delta:number)=>void;onReset:()=>void}){const start=useRef(0);const delta=useRef(0);const resizable=COLUMN_LAYOUT[column].resizable!==false;const begin=(event:React.PointerEvent)=>{if(!resizable)return;event.preventDefault();start.current=event.clientX;delta.current=0;const move=(moveEvent:PointerEvent)=>{delta.current=moveEvent.clientX-start.current;onDrag(delta.current);};const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);onCommit(delta.current);};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up);};return <span className="relative flex h-full min-w-0 items-center truncate px-1"><span className="truncate">{COLUMN_LABELS[column]}</span>{resizable&&<span role="separator" aria-label={`调整${COLUMN_LABELS[column]}列宽`} aria-orientation="vertical" aria-valuemin={COLUMN_LAYOUT[column].min} aria-valuemax={COLUMN_LAYOUT[column].max??800} aria-valuenow={width} tabIndex={0} className="absolute right-0 top-1 h-7 w-2 cursor-col-resize border-r-2 border-transparent hover:border-primary-500 focus:border-primary-500 focus:outline-none" onPointerDown={begin} onDoubleClick={onReset} onKeyDown={event=>{if(event.key==="Enter"){onReset();return;}if(event.key!=="ArrowLeft"&&event.key!=="ArrowRight")return;event.preventDefault();const amount=event.shiftKey?24:8;onCommit(event.key==="ArrowRight"?amount:-amount);}}/>}</span>;}

function MeasuredRow({row,rowKey,top,height,minimumHeight,columns,template,appearance,selected,onMeasured,onToggle,onComplexEdit}:{row:PaperListRow;rowKey:string;top:number;height:number;minimumHeight:number;columns:PaperListColumn[];template:string;appearance:PaperListAppearance;selected:boolean;onMeasured:(value:number)=>void;onToggle:()=>void;onComplexEdit:(id:string)=>void}){const rowRef=useRef<HTMLDivElement>(null);useLayoutEffect(()=>{const node=rowRef.current;if(!node)return;const measure=()=>{const sources=[...node.querySelectorAll<HTMLElement>("[data-height-source]")];const required=Math.max(minimumHeight,...sources.map(source=>source.scrollHeight+10));onMeasured(Math.ceil(required));};measure();const observer=new ResizeObserver(measure);node.querySelectorAll("[data-height-source]").forEach(source=>observer.observe(source));return()=>observer.disconnect();},[minimumHeight,onMeasured,rowKey]);return <div ref={rowRef} className="absolute inset-x-0 grid items-stretch border-b px-1" style={{top,height,minHeight:minimumHeight,gridTemplateColumns:template,background:selected?appearance.selected_background:appearance.row_background,borderColor:appearance.border}} onMouseEnter={e=>{if(!selected)e.currentTarget.style.background=appearance.hover_background;}} onMouseLeave={e=>{e.currentTarget.style.background=selected?appearance.selected_background:appearance.row_background;}}><div className="flex items-center"><input type="checkbox" aria-label={`选择论文 ${row.title}`} checked={selected} onChange={onToggle}/></div>{columns.map(column=><div key={column} className={`min-h-0 min-w-0 overflow-hidden px-1 ${column==="title"||column==="title_zh"?"py-1":"flex items-center"}`}><Cell row={row} column={column} linkColor={appearance.link} onComplexEdit={onComplexEdit} titleSource={column==="title"||column==="title_zh"}/></div>)}</div>;}

function Cell({row,column,linkColor,onComplexEdit,titleSource=false}:{row:PaperListRow;column:PaperListColumn;linkColor:string;onComplexEdit:(id:string)=>void;titleSource?:boolean}) {
  if (["authors","keywords","tags","folders"].includes(column)) { const items=column==="authors"?row.authors:row[column as "keywords"|"tags"|"folders"];return <button className="group flex w-full items-center gap-1 truncate text-left" title={items.map(x=>x.name).join("; ")} onClick={()=>onComplexEdit(row.id)}><span className="truncate">{items.map(x=>x.name).join("; ")||"—"}</span><Pencil className="hidden h-3 w-3 shrink-0 group-hover:block"/></button>; }
  if(column==="notes")return <Link style={{color:linkColor}} to={`/papers/${row.id}/notes`}>{row.note_count} 篇</Link>;
  if(column==="reading_status")return <span>{readingLabels[row.reading_status]||row.reading_status}</span>;
  if(column==="created_at"||column==="updated_at")return <>{new Date(row[column]).toLocaleDateString("zh-CN")}</>;
  if(editable.has(column))return <EditableCell row={row} column={column} linkColor={linkColor} titleSource={titleSource}/>;
  return <>—</>;
}

function EditableCell({row,column,linkColor,titleSource}:{row:PaperListRow;column:PaperListColumn;linkColor:string;titleSource:boolean}) {
  const mutation=useUpdatePaperCell(); const raw=column==="starred"?row.starred:row[column as keyof PaperListRow];
  const text=column==="starred"?(row.starred?"★":"☆"):String(raw??"—"); const [editing,setEditing]=useState(false); const [value,setValue]=useState(String(raw??"")); const [saved,setSaved]=useState(false);
  const save=async()=>{let next:string|number|boolean|null=value.trim()||null;if(column==="publication_year"||column==="citation_count")next=value.trim()?Number(value):null;if(column==="starred")next=!row.starred;const data={expected_revision:row.metadata_revision,[column==="starred"?"is_starred":column]:next} as PaperCellUpdate;try{await mutation.mutateAsync({paperId:row.id,data});setEditing(false);setSaved(true);setTimeout(()=>setSaved(false),1000);}catch(error){const status=(error as {response?:{status?:number}}).response?.status;alert(status===409?"论文信息已在其他页面发生修改，请刷新后重新编辑。":"保存失败，请重试。");}};
  if(column==="title"&&!editing)return <Link data-height-source={titleSource||undefined} to={`/reader/${row.id}`} style={{color:linkColor,whiteSpace:"normal",overflowWrap:"anywhere",wordBreak:"break-word"}} className="block font-medium leading-snug" title={row.title} onDoubleClick={e=>{e.preventDefault();setValue(row.title);setEditing(true);}}>{row.title}</Link>;
  if(column==="starred")return <button className="text-base" title="切换收藏" onClick={save}>{mutation.isPending?<LoaderCircle className="h-3 w-3 animate-spin"/>:text}</button>;
  if(editing&&longText.has(column))return <LongTextEditor title={COLUMN_LABELS[column]} value={value} onChange={setValue} onSave={save} onClose={()=>setEditing(false)} saving={mutation.isPending}/>;
  if(editing)return <input autoFocus className="w-full rounded border px-1 py-0.5" value={value} onChange={e=>setValue(e.target.value)} onBlur={save} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur();if(e.key==="Escape")setEditing(false);}}/>;
  return <button data-height-source={titleSource||undefined} className={`w-full text-left ${titleSource?"block whitespace-normal break-words leading-snug":"flex items-center gap-1 truncate"}`} style={titleSource?{overflowWrap:"anywhere",wordBreak:"break-word"}:undefined} title={text} onDoubleClick={()=>{setValue(String(raw??""));setEditing(true);}} onClick={()=>longText.has(column)&&setEditing(true)}><span className={titleSource?"":"truncate"}>{text}</span>{mutation.isPending?<LoaderCircle className="h-3 w-3 animate-spin"/>:saved?<Check className="h-3 w-3 text-green-600"/>:null}</button>;
}

function LongTextEditor({title,value,onChange,onSave,onClose,saving}:{title:string;value:string;onChange:(x:string)=>void;onSave:()=>void;onClose:()=>void;saving:boolean}) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-6" role="dialog" aria-modal="true" aria-label={`编辑${title}`}><div className="w-full max-w-2xl rounded-xl bg-white p-4 shadow-xl dark:bg-slate-900"><h3 className="mb-2 font-semibold">编辑{title}</h3><textarea autoFocus className="input min-h-64 w-full" value={value} onChange={e=>onChange(e.target.value)}/><div className="mt-3 flex justify-end gap-2"><button className="btn-ghost" onClick={onClose}>取消</button><button className="btn-primary" disabled={saving} onClick={onSave}>{saving?"保存中…":"保存"}</button></div></div></div>; }
