"""s16 ai translation chat infrastructure

Revision ID: 44ef08614b89
Revises: a1c5e8f3b7d9
Create Date: 2026-08-20 12:59:34.502683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '44ef08614b89'
down_revision: Union[str, None] = 'a1c5e8f3b7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_budget_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.String(length=32), server_default='global', nullable=False),
    sa.Column('scope_id', sa.String(length=255), nullable=True),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('token_limit', sa.Integer(), nullable=True),
    sa.Column('cost_limit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('currency', sa.String(length=8), server_default='USD', nullable=False),
    sa.Column('hard_limit', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('warning_threshold', sa.Numeric(precision=5, scale=4), server_default='0.8', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("period_type IN ('per_request','daily','weekly','monthly','lifetime')", name='ck_ai_budget_period'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope_type', 'scope_id', 'period_type', name='uq_ai_budget_scope_period')
    )
    op.create_index(op.f('ix_ai_budget_policies_user_id'), 'ai_budget_policies', ['user_id'], unique=False)
    op.create_table('ai_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider_type', sa.String(length=40), server_default='openai_compatible', nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('is_local', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), server_default='120', nullable=False),
    sa.Column('max_concurrency', sa.Integer(), server_default='2', nullable=False),
    sa.Column('capabilities', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_ai_providers_user_name')
    )
    op.create_index(op.f('ix_ai_providers_user_id'), 'ai_providers', ['user_id'], unique=False)
    op.create_table('translation_glossary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_language', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('source_term', sa.String(length=255), nullable=False),
    sa.Column('target_term', sa.String(length=255), nullable=True),
    sa.Column('case_sensitive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('do_not_translate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('scope_type', sa.String(length=20), server_default='global', nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_language', 'target_language', 'source_term', 'scope_type', 'scope_id', name='uq_translation_glossary_term')
    )
    op.create_index(op.f('ix_translation_glossary_user_id'), 'translation_glossary', ['user_id'], unique=False)
    op.create_table('ai_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('capabilities', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_name', name='uq_ai_models_provider_name')
    )
    op.create_index(op.f('ix_ai_models_provider_id'), 'ai_models', ['provider_id'], unique=False)
    op.create_table('ai_chat_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), server_default='New chat', nullable=False),
    sa.Column('scope_type', sa.String(length=24), server_default='paper', nullable=False),
    sa.Column('scope_snapshot', sa.JSON(), nullable=True),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('system_prompt_version', sa.String(length=40), server_default='reader-qa-v1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_sessions_paper_id'), 'ai_chat_sessions', ['paper_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_user_id'), 'ai_chat_sessions', ['user_id'], unique=False)
    op.create_index('ix_ai_chat_sessions_user_paper_updated', 'ai_chat_sessions', ['user_id', 'paper_id', 'updated_at'], unique=False)
    op.create_table('ai_model_pricing',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='USD', nullable=False),
    sa.Column('input_per_million', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cached_input_per_million', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('output_per_million', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_model_pricing_model_id'), 'ai_model_pricing', ['model_id'], unique=False)
    op.create_table('ai_request_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('paper_id', sa.Uuid(), nullable=True),
    sa.Column('feature', sa.String(length=40), nullable=False),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='reserved', nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default='1', nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('token_source', sa.String(length=24), server_default='estimate', nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('cost_status', sa.String(length=24), server_default='unknown', nullable=False),
    sa.Column('price_snapshot', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('safe_error', sa.Text(), nullable=True),
    sa.Column('context_type', sa.String(length=40), nullable=True),
    sa.Column('context_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_request_records_feature'), 'ai_request_records', ['feature'], unique=False)
    op.create_index(op.f('ix_ai_request_records_status'), 'ai_request_records', ['status'], unique=False)
    op.create_index(op.f('ix_ai_request_records_user_id'), 'ai_request_records', ['user_id'], unique=False)
    op.create_index('ix_ai_requests_user_created', 'ai_request_records', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_ai_requests_user_feature_created', 'ai_request_records', ['user_id', 'feature', 'created_at'], unique=False)
    op.create_index('ix_ai_requests_user_paper_created', 'ai_request_records', ['user_id', 'paper_id', 'created_at'], unique=False)
    op.create_table('paper_translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('source_pdf_hash', sa.String(length=64), nullable=False),
    sa.Column('source_language', sa.String(length=16), server_default='en', nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('parser_version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_translations_document_id'), 'paper_translations', ['document_id'], unique=False)
    op.create_index(op.f('ix_paper_translations_paper_id'), 'paper_translations', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_translations_user_id'), 'paper_translations', ['user_id'], unique=False)
    op.create_index('ix_paper_translations_user_paper_active', 'paper_translations', ['user_id', 'paper_id', 'is_active'], unique=False)
    op.create_table('ai_budget_reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('budget_policy_id', sa.Uuid(), nullable=False),
    sa.Column('reserved_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reserved_cost', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budget_policy_id'], ['ai_budget_policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['ai_request_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_budget_reservations_budget_policy_id'), 'ai_budget_reservations', ['budget_policy_id'], unique=False)
    op.create_index(op.f('ix_ai_budget_reservations_request_id'), 'ai_budget_reservations', ['request_id'], unique=False)
    op.create_index(op.f('ix_ai_budget_reservations_user_id'), 'ai_budget_reservations', ['user_id'], unique=False)
    op.create_index('ix_ai_reservations_user_status_expiry', 'ai_budget_reservations', ['user_id', 'status', 'expires_at'], unique=False)
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='completed', nullable=False),
    sa.Column('request_record_id', sa.Uuid(), nullable=True),
    sa.Column('input_scope_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_record_id'], ['ai_request_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_chat_messages_session_created', 'ai_chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_session_id'), 'ai_chat_messages', ['session_id'], unique=False)
    op.create_table('page_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('block_order', sa.Integer(), nullable=False),
    sa.Column('reading_order', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=32), server_default='paragraph', nullable=False),
    sa.Column('column_index', sa.Integer(), nullable=True),
    sa.Column('parent_block_id', sa.Uuid(), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_block_id'], ['page_blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', 'block_order', name='uq_page_blocks_document_page_order')
    )
    op.create_index(op.f('ix_page_blocks_document_id'), 'page_blocks', ['document_id'], unique=False)
    op.create_index('ix_page_blocks_document_reading', 'page_blocks', ['document_id', 'page_number', 'reading_order'], unique=False)
    op.create_index(op.f('ix_page_blocks_paper_id'), 'page_blocks', ['paper_id'], unique=False)
    op.create_index(op.f('ix_page_blocks_section_id'), 'page_blocks', ['section_id'], unique=False)
    op.create_index(op.f('ix_page_blocks_source_hash'), 'page_blocks', ['source_hash'], unique=False)
    op.create_table('translation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('paper_translation_id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.String(length=24), nullable=False),
    sa.Column('scope_start', sa.Integer(), nullable=True),
    sa.Column('scope_end', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('source_language', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('block_ids', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('total_blocks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completed_blocks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_blocks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_translation_id'], ['paper_translations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_jobs_paper_id'), 'translation_jobs', ['paper_id'], unique=False)
    op.create_index(op.f('ix_translation_jobs_paper_translation_id'), 'translation_jobs', ['paper_translation_id'], unique=False)
    op.create_index(op.f('ix_translation_jobs_status'), 'translation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_translation_jobs_user_id'), 'translation_jobs', ['user_id'], unique=False)
    op.create_index('ix_translation_jobs_user_paper_created', 'translation_jobs', ['user_id', 'paper_id', 'created_at'], unique=False)
    op.create_table('ai_message_citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_id', sa.Uuid(), nullable=True),
    sa.Column('page_block_id', sa.Uuid(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('citation_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['ai_chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_block_id'], ['page_blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_message_citations_message_id'), 'ai_message_citations', ['message_id'], unique=False)
    op.create_index('ix_ai_message_citations_message_order', 'ai_message_citations', ['message_id', 'citation_order'], unique=False)
    op.create_index(op.f('ix_ai_message_citations_paper_id'), 'ai_message_citations', ['paper_id'], unique=False)
    op.create_table('translation_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paper_translation_id', sa.Uuid(), nullable=False),
    sa.Column('page_block_id', sa.Uuid(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('machine_translation', sa.Text(), nullable=True),
    sa.Column('user_translation', sa.Text(), nullable=True),
    sa.Column('provider_name', sa.String(length=120), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('translated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['page_block_id'], ['page_blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_translation_id'], ['paper_translations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_translation_id', 'page_block_id', name='uq_translation_block_source')
    )
    op.create_index(op.f('ix_translation_blocks_page_block_id'), 'translation_blocks', ['page_block_id'], unique=False)
    op.create_index(op.f('ix_translation_blocks_paper_translation_id'), 'translation_blocks', ['paper_translation_id'], unique=False)
    op.add_column('papers', sa.Column('ai_access_policy', sa.String(length=20), server_default='allow_cloud', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'ai_access_policy')
    op.drop_index(op.f('ix_translation_blocks_paper_translation_id'), table_name='translation_blocks')
    op.drop_index(op.f('ix_translation_blocks_page_block_id'), table_name='translation_blocks')
    op.drop_table('translation_blocks')
    op.drop_index(op.f('ix_ai_message_citations_paper_id'), table_name='ai_message_citations')
    op.drop_index('ix_ai_message_citations_message_order', table_name='ai_message_citations')
    op.drop_index(op.f('ix_ai_message_citations_message_id'), table_name='ai_message_citations')
    op.drop_table('ai_message_citations')
    op.drop_index('ix_translation_jobs_user_paper_created', table_name='translation_jobs')
    op.drop_index(op.f('ix_translation_jobs_user_id'), table_name='translation_jobs')
    op.drop_index(op.f('ix_translation_jobs_status'), table_name='translation_jobs')
    op.drop_index(op.f('ix_translation_jobs_paper_translation_id'), table_name='translation_jobs')
    op.drop_index(op.f('ix_translation_jobs_paper_id'), table_name='translation_jobs')
    op.drop_table('translation_jobs')
    op.drop_index(op.f('ix_page_blocks_source_hash'), table_name='page_blocks')
    op.drop_index(op.f('ix_page_blocks_section_id'), table_name='page_blocks')
    op.drop_index(op.f('ix_page_blocks_paper_id'), table_name='page_blocks')
    op.drop_index('ix_page_blocks_document_reading', table_name='page_blocks')
    op.drop_index(op.f('ix_page_blocks_document_id'), table_name='page_blocks')
    op.drop_table('page_blocks')
    op.drop_index(op.f('ix_ai_chat_messages_session_id'), table_name='ai_chat_messages')
    op.drop_index('ix_ai_chat_messages_session_created', table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    op.drop_index('ix_ai_reservations_user_status_expiry', table_name='ai_budget_reservations')
    op.drop_index(op.f('ix_ai_budget_reservations_request_id'), table_name='ai_budget_reservations')
    op.drop_index(op.f('ix_ai_budget_reservations_user_id'), table_name='ai_budget_reservations')
    op.drop_index(op.f('ix_ai_budget_reservations_budget_policy_id'), table_name='ai_budget_reservations')
    op.drop_table('ai_budget_reservations')
    op.drop_index('ix_paper_translations_user_paper_active', table_name='paper_translations')
    op.drop_index(op.f('ix_paper_translations_user_id'), table_name='paper_translations')
    op.drop_index(op.f('ix_paper_translations_paper_id'), table_name='paper_translations')
    op.drop_index(op.f('ix_paper_translations_document_id'), table_name='paper_translations')
    op.drop_table('paper_translations')
    op.drop_index('ix_ai_requests_user_paper_created', table_name='ai_request_records')
    op.drop_index('ix_ai_requests_user_feature_created', table_name='ai_request_records')
    op.drop_index('ix_ai_requests_user_created', table_name='ai_request_records')
    op.drop_index(op.f('ix_ai_request_records_user_id'), table_name='ai_request_records')
    op.drop_index(op.f('ix_ai_request_records_status'), table_name='ai_request_records')
    op.drop_index(op.f('ix_ai_request_records_feature'), table_name='ai_request_records')
    op.drop_table('ai_request_records')
    op.drop_index(op.f('ix_ai_model_pricing_model_id'), table_name='ai_model_pricing')
    op.drop_table('ai_model_pricing')
    op.drop_index('ix_ai_chat_sessions_user_paper_updated', table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_user_id'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_paper_id'), table_name='ai_chat_sessions')
    op.drop_table('ai_chat_sessions')
    op.drop_index(op.f('ix_ai_models_provider_id'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_translation_glossary_user_id'), table_name='translation_glossary')
    op.drop_table('translation_glossary')
    op.drop_index(op.f('ix_ai_providers_user_id'), table_name='ai_providers')
    op.drop_table('ai_providers')
    op.drop_index(op.f('ix_ai_budget_policies_user_id'), table_name='ai_budget_policies')
    op.drop_table('ai_budget_policies')
    # ### end Alembic commands ###
